/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TrainService } from "../train.service";
import { TrainCreateInput } from "./TrainCreateInput";
import { Train } from "./Train";
import { TrainFindManyArgs } from "./TrainFindManyArgs";
import { TrainWhereUniqueInput } from "./TrainWhereUniqueInput";
import { TrainUpdateInput } from "./TrainUpdateInput";

export class TrainControllerBase {
  constructor(protected readonly service: TrainService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Train })
  async createTrain(@common.Body() data: TrainCreateInput): Promise<Train> {
    return await this.service.createTrain({
      data: data,
      select: {
        createdAt: true,
        id: true,
        trainName: true,
        trainNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Train] })
  @ApiNestedQuery(TrainFindManyArgs)
  async trains(@common.Req() request: Request): Promise<Train[]> {
    const args = plainToClass(TrainFindManyArgs, request.query);
    return this.service.trains({
      ...args,
      select: {
        createdAt: true,
        id: true,
        trainName: true,
        trainNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Train })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async train(
    @common.Param() params: TrainWhereUniqueInput
  ): Promise<Train | null> {
    const result = await this.service.train({
      where: params,
      select: {
        createdAt: true,
        id: true,
        trainName: true,
        trainNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Train })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTrain(
    @common.Param() params: TrainWhereUniqueInput,
    @common.Body() data: TrainUpdateInput
  ): Promise<Train | null> {
    try {
      return await this.service.updateTrain({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          trainName: true,
          trainNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Train })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTrain(
    @common.Param() params: TrainWhereUniqueInput
  ): Promise<Train | null> {
    try {
      return await this.service.deleteTrain({
        where: params,
        select: {
          createdAt: true,
          id: true,
          trainName: true,
          trainNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
