/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Train } from "./Train";
import { TrainCountArgs } from "./TrainCountArgs";
import { TrainFindManyArgs } from "./TrainFindManyArgs";
import { TrainFindUniqueArgs } from "./TrainFindUniqueArgs";
import { CreateTrainArgs } from "./CreateTrainArgs";
import { UpdateTrainArgs } from "./UpdateTrainArgs";
import { DeleteTrainArgs } from "./DeleteTrainArgs";
import { TrainService } from "../train.service";
@graphql.Resolver(() => Train)
export class TrainResolverBase {
  constructor(protected readonly service: TrainService) {}

  async _trainsMeta(
    @graphql.Args() args: TrainCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Train])
  async trains(@graphql.Args() args: TrainFindManyArgs): Promise<Train[]> {
    return this.service.trains(args);
  }

  @graphql.Query(() => Train, { nullable: true })
  async train(
    @graphql.Args() args: TrainFindUniqueArgs
  ): Promise<Train | null> {
    const result = await this.service.train(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Train)
  async createTrain(@graphql.Args() args: CreateTrainArgs): Promise<Train> {
    return await this.service.createTrain({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Train)
  async updateTrain(
    @graphql.Args() args: UpdateTrainArgs
  ): Promise<Train | null> {
    try {
      return await this.service.updateTrain({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Train)
  async deleteTrain(
    @graphql.Args() args: DeleteTrainArgs
  ): Promise<Train | null> {
    try {
      return await this.service.deleteTrain(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
