/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Train as PrismaTrain } from "@prisma/client";

export class TrainServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.TrainCountArgs, "select">): Promise<number> {
    return this.prisma.train.count(args);
  }

  async trains(args: Prisma.TrainFindManyArgs): Promise<PrismaTrain[]> {
    return this.prisma.train.findMany(args);
  }
  async train(args: Prisma.TrainFindUniqueArgs): Promise<PrismaTrain | null> {
    return this.prisma.train.findUnique(args);
  }
  async createTrain(args: Prisma.TrainCreateArgs): Promise<PrismaTrain> {
    return this.prisma.train.create(args);
  }
  async updateTrain(args: Prisma.TrainUpdateArgs): Promise<PrismaTrain> {
    return this.prisma.train.update(args);
  }
  async deleteTrain(args: Prisma.TrainDeleteArgs): Promise<PrismaTrain> {
    return this.prisma.train.delete(args);
  }
}
